### ISSUE TITLE
Broken link in `data-structure.md`

### ISSUE THREAD

**Issue by huggablemonad** [CarnegieHall/linked-data#10]
Specifically, the "HTML representation" of the "sample event record" link is broken (404 error):

https://www.carnegiehall.org/widgets/opas/concert.aspx?id=8195

**Comment by robertmhudson** [comment]
Thanks for bringing this to our attention. We’ll be updating the entire repo soon and will address this issue as part of that work.

**Comment by kgrons** [comment]
done! thanks @huggablemonad
