### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by SeekPoint** [CarnegieHall/linked-data#11]

**Comment by robertmhudson** [comment]
I'm not sure I understand the issue or question. Could you provide more detail?

**Comment by SeekPoint** [comment]
some demo, so I can figure it out what's doing

**Comment by robertmhudson** [comment]
It’s not an application; the repo documents the open release of Carnegie Hall’s performance history data, and it’s structure and creation. Is there something specific you were trying to do? Perhaps take a look at the [README](https://github.com/CarnegieHall/linked-data/blob/master/README.md), and then open a new issue with a specific problem or task you were hoping to accomplish.
