### ISSUE TITLE
Make the SPARQL endpoint CORS enabled

### ISSUE THREAD

**Issue by wouterbeek** [CarnegieHall/linked-data#6]
The SPARQL endpoint is currently not CORS enabled.  This means that other web pages cannot send requests to the SPARQL endpoint.  Specifically, they will receive the following error (where `$(ORIGIN)` is the URL of the application that tries to send a SPARQL request):

```
Failed to load http://data.carnegiehall.org/sparql/select?query=ASK%20%7B%3Fx%20%3Fy%20%3Fz%7D: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin $(ORIGIN) is therefore not allowed access.
```

**Comment by robertmhudson** [comment]
Thanks for your helpful input. We have addressed this (better late than never!), in the repo where the endpoint app is managed: https://github.com/CarnegieHall/ch-lod-app/commit/38f44d653d3e9b84a0ca71384eb5a901f822fa45
